### ISSUE TITLE
Cards "working".

### ISSUE THREAD

**Issue by oatmealformana** [MikaSchoenmakers/MikasBalatro#1]
Specifically Batman and The Show-Off, their specials trigger but never add to their own mult. Batman does +1 mult, but doesn't add it to his card and The Show-Off gives a 1x multiplier (does nothing) and doesn't add anything to it's own card after finishing a blind with 2x the chip requirement.

And yes, I read the descriptions right. I'm playing my cards right. This mod just adds several broken jokers.

**Comment by MikaSchoenmakers** [comment]
Could you verify if this problem happens without any other mods installed?

**Comment by oatmealformana** [comment]
Can verify it only happens while using JellyJokers

**Comment by MikaSchoenmakers** [comment]
This might've been fixed in the newest update that just got released. Have you updated to the latest version? And if not could you try that?

**Comment by oatmealformana** [comment]
Can confirm it does NOT work in the latest version, or at least Batman still doesn't. Turning off JellyJokers fixes it, though.

**Comment by oatmealformana** [comment]
was not JellyJokers, it was some other thing in there with it called Jokers.md

**Comment by MikaSchoenmakers** [comment]
That is incredibly odd. I don't see how that would affect my mod at all. I will try to see if I can find a fix tomorrow!

**Comment by MikaSchoenmakers** [comment]
I am unable to reproduce this with any Jokers.md file being inside the Mods folder. I assume it's JellyMod that is causing issues, seeing that it states that it is not compatible with most other mods [here](https://github.com/jamesthejellyfish/JellyMod?tab=readme-ov-file#compatibility-warning). Unfortunately that is completely out of my control, but you could consider posting about it on their github instead.
